import { db } from './client';

export async function initDb() {
  const quoteCount = await db.quotes.count();
  if (quoteCount === 0) {
    const quotes = [
      { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
      { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
      { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
      { text: "The clock is ticking. Are you becoming the person you want to be?", author: "Greg Plitt" },
      { text: "Whether you think you can, or you think you can't, you're right.", author: "Henry Ford" },
      { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
      { text: "Discipline is doing what needs to be done, even if you don't want to do it.", author: "Unknown" },
      { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
      { text: "I hated every minute of training, but I said, 'Don't quit. Suffer now and live the rest of your life as a champion.'", author: "Muhammad Ali" },
      { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
      { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
      { text: "Hard days are the best days because that's when champions are made.", author: "Gabby Douglas" },
      { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
      { text: "Your body can stand almost anything. It’s your mind that you have to convince.", author: "Unknown" },
      { text: "The only way to define your limits is by going beyond them.", author: "Arthur C. Clarke" },
      { text: "Today I will do what others won't, so tomorrow I can accomplish what others can't.", author: "Jerry Rice" },
      { text: "Small progress is still progress.", author: "Unknown" },
      { text: "The hard part isn't getting your body in shape. The hard part is getting your mind in shape.", author: "Unknown" },
      { text: "Look in the mirror. That’s your competition.", author: "Unknown" },
      { text: "Tough times don't last. Tough people do.", author: "Robert H. Schuller" },
      { text: "A one-hour workout is only 4% of your day. No excuses.", author: "Unknown" },
      { text: "Pain is temporary. Quitting lasts forever.", author: "Lance Armstrong" },
      { text: "Bodybuilding is much like any other sport. To be successful, you must dedicate yourself 100% to your training, diet and mental approach.", author: "Arnold Schwarzenegger" },
      { text: "The last three or four reps is what makes the muscle grow. This area of pain divides a champion from someone who is not a champion.", author: "Arnold Schwarzenegger" },
      { text: "Everything is hard before it is easy.", author: "Goethe" },
      { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
      { text: "Great things never come from comfort zones.", author: "Unknown" },
      { text: "If it doesn't challenge you, it doesn't change you.", author: "Fred DeVito" },
      { text: "Fitness is not about being better than someone else. It’s about being better than you were yesterday.", author: "Unknown" },
      { text: "Don't decrease the goal. Increase the effort.", author: "Unknown" },
      { text: "What seems impossible today will one day become your warm-up.", author: "Unknown" },
      { text: "Exercise is labor without weariness.", author: "Samuel Johnson" },
      { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
      { text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Robert Tew" },
      { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
      { text: "Confidence comes from discipline and training.", author: "Robert Kiyosaki" },
      { text: "Your health is an investment, not an expense.", author: "Unknown" },
      { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
      { text: "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it.", author: "Arnold Schwarzenegger" },
      { text: "All our dreams can come true, if we have the courage to pursue them.", author: "Walt Disney" },
      { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
      { text: "It’s going to be a journey. It’s not a sprint to get in shape.", author: "Kerri Walsh Jennings" },
      { text: "I’ve failed over and over and over again in my life and that is why I succeed.", author: "Michael Jordan" },
      { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
      { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
      { text: "Don’t stop when you’re tired. Stop when you’re done.", author: "Unknown" },
      { text: "The difference between the impossible and the possible lies in a person’s determination.", author: "Tommy Lasorda" },
      { text: "If you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
      { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
      { text: "The starting point of all achievement is desire.", author: "Napoleon Hill" },
      { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
      { text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
      { text: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
      { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
      { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
      { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
      { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
      { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
      { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
      { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
      { text: "I have nothing in common with lazy people who blame others for their lack of success.", author: "Kobe Bryant" },
      { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
      { text: "You must do the things you think you cannot do.", author: "Eleanor Roosevelt" },
      { text: "The more you sweat in training, the less you bleed in combat.", author: "Navy SEAL Motto" },
      { text: "Do something today that your future self will thank you for.", author: "Unknown" },
      { text: "A year from now you may wish you had started today.", author: "Karen Lamb" },
      { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
      { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
      { text: "If you can dream it, you can do it.", author: "Walt Disney" },
      { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
      { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
      { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
      { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
      { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
      { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
      { text: "Aim for the moon. If you miss, you may hit a star.", author: "W. Clement Stone" },
      { text: "Keep your face always toward the sunshine - and shadows will fall behind you.", author: "Walt Whitman" },
      { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
      { text: "Happiness is not something readymade. It comes from your own actions.", author: "Dalai Lama" },
      { text: "Believe in yourself! Have faith in your abilities!", author: "Norman Vincent Peale" },
      { text: "The power of imagination makes us infinite.", author: "John Muir" },
      { text: "Every day provides its own gifts.", author: "Marcus Aurelius" },
      { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
      { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown, Jr." },
      { text: "Reach for the stars, even if you have to stand on a cactus.", author: "Unknown" },
      { text: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
      { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
      { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
      { text: "You do not find a happy life. You make it.", author: "Camilla Eyring Kimball" },
      { text: "Make each day your masterpiece.", author: "John Wooden" },
      { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
      { text: "Consistency is the mother of mastery.", author: "Robin Sharma" },
      { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
      { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
      { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
      { text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
      { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Dennis P. Kimbro" },
      { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
      { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
      { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    ].map(q => ({ ...q, lastShown: null }));

    await db.quotes.bulkAdd(quotes);
  }

  const stats = await db.userStats.get('current');
  if (!stats) {
    await db.userStats.add({
      id: 'current',
      rank: 'Iron',
      currentXp: 0,
      streak: 0,
      lastWorkout: null,
      battery: 100,
    });
  }
}
